const peopleList = document.querySelector('#peopleList');
const treeCanvas = document.querySelector('#treeCanvas');
const connections = document.querySelector('#connections');
const yearBands = document.querySelector('#yearBands');
const branchActions = document.querySelector('#branchActions');
const dialog = document.querySelector('#personDialog');
const loadDialog = document.querySelector('#loadDialog');
const saveDialog = document.querySelector('#saveDialog');
const createForm = document.querySelector('#createForm');
const loadForm = document.querySelector('#loadForm');
const saveForm = document.querySelector('#saveForm');
const editForm = document.querySelector('#editForm');
const emptyAdd = document.querySelector('#emptyAdd');
const addDisconnected = document.querySelector('#addDisconnected');
const editFather = document.querySelector('#editFather');
const editMother = document.querySelector('#editMother');
const editSpouse = document.querySelector('#editSpouse');
const editGender = document.querySelector('#editGender');
const savedTree = document.querySelector('#savedTree');
const saveName = document.querySelector('#saveName');
let people = [];
let selectedId = null;
let positions = new Map();
let simulation = null;

async function request(url, options) { const response = await fetch(url, options); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Request failed'); return result; }
function escapeHtml(value) { return value.replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[character])); }
function personName(id) { return people.find(person => person.id === id)?.name || 'Unknown'; }
function apiDate(value) { if (!value) return ''; const [year, month, day] = value.split('-'); return `${month}-${day}-${year}`; }
function inputDate(value) { if (!value) return ''; const [month, day, year] = value.split('-'); return year ? `${year}-${month}-${day}` : value; }
function normalizePerson(person) { return { ...person, birthday: typeof person.birthday === 'string' ? person.birthday : '', gender: person.gender === 'male' || person.gender === 'female' ? person.gender : 'unknown', children: Array.isArray(person.children) ? person.children : [], spouses: Array.isArray(person.spouses) ? person.spouses : [], siblings: Array.isArray(person.siblings) ? person.siblings : [] }; }
function relationshipCount(person) { return (person.father !== null ? 1 : 0) + (person.mother !== null ? 1 : 0) + (Array.isArray(person.children) ? person.children.length : 0) + (Array.isArray(person.spouses) ? person.spouses.length : 0); }
function yearOf(person) { return Number((person.birthday || '').slice(-4)) || 0; }
function relationshipOptions(selectedId, includeBlank = false, eligible = () => true) { const options = includeBlank ? '<option value="">None</option>' : ''; return options + people.filter(person => person.id !== selectedId && eligible(person)).sort((a, b) => a.name.localeCompare(b.name)).map(person => `<option value="${person.id}">${escapeHtml(person.name)}</option>`).join(''); }
function populateRelationshipFields(person) { const relatedIds = new Set([person.father, person.mother, ...person.children, ...person.siblings].filter(id => id !== null)); editFather.innerHTML = relationshipOptions(person.id, true); editMother.innerHTML = relationshipOptions(person.id, true); editSpouse.innerHTML = relationshipOptions(person.id, true, candidate => !relatedIds.has(candidate.id) || person.spouses.includes(candidate.id)); editFather.value = person.father ?? ''; editMother.value = person.mother ?? ''; editSpouse.value = person.spouses[0] ?? ''; editGender.value = person.gender; }
function generationMap() {
  const center = [...people].sort((a, b) => relationshipCount(b) - relationshipCount(a))[0];
  const generations = new Map(people.map(person => [person.id, null]));
  if (!center) return new Map();
  generations.set(center.id, 0); const queue = [center];
  while (queue.length) { const current = queue.shift(); const level = generations.get(current.id); const neighbors = [...[current.father, current.mother].filter(id => id !== null).map(id => [id, level - 1]), ...current.children.map(id => [id, level + 1]), ...current.spouses.map(id => [id, level])]; neighbors.forEach(([id, nextLevel]) => { if (generations.get(id) === null) { generations.set(id, nextLevel); queue.push(people.find(person => person.id === id)); } }); }
  generations.forEach((value, id) => { if (value === null) generations.set(id, 0); }); const minimum = Math.min(...generations.values(), 0); generations.forEach((value, id) => generations.set(id, value - minimum)); return generations;
}
function layoutGraph(generations, viewportWidth) {
  const nodeWidth = 180; const nodeGap = 42; const spacing = nodeWidth + nodeGap; const rowGap = 190; const maxYear = Math.max(...people.map(yearOf), 0); const minYear = Math.min(...people.filter(person => yearOf(person)).map(yearOf), maxYear || new Date().getFullYear());
  const masses = new Map(people.map(person => { const year = yearOf(person); const ageFactor = year ? (maxYear - year) / Math.max(1, maxYear - minYear) : (Math.max(...generations.values()) - generations.get(person.id)) / Math.max(1, Math.max(...generations.values())); return [person.id, viewportWidth * (0.018 + 0.012 * Math.max(0, Math.min(1, ageFactor)))]; }));
  const components = new Map(); let componentCount = 0; people.forEach(person => { if (components.has(person.id)) return; const queue = [person.id]; components.set(person.id, componentCount); while (queue.length) { const id = queue.shift(); const current = people.find(entry => entry.id === id); const linked = [current.father, current.mother, ...current.children, ...current.spouses].filter(linkedId => linkedId !== null); linked.forEach(linkedId => { if (!components.has(linkedId)) { components.set(linkedId, componentCount); queue.push(linkedId); } }); } componentCount += 1; });
  const groups = new Map(); people.forEach(person => { const generation = generations.get(person.id) ?? 0; if (!groups.has(generation)) groups.set(generation, []); groups.get(generation).push(person); });
  const componentGap = Math.max(viewportWidth * 0.7, spacing * 3); const targets = new Map(); const centers = new Map(); for (let index = 0; index < componentCount; index += 1) centers.set(index, (index - (componentCount - 1) / 2) * componentGap);
  people.forEach(person => { const parents = [person.father, person.mother].filter(id => id !== null); const siblings = parents.length ? people.filter(candidate => candidate.father === person.father && candidate.mother === person.mother) : []; const siblingIndex = siblings.findIndex(sibling => sibling.id === person.id); const parentCenter = parents.length ? parents.reduce((sum, id) => sum + (targets.get(id) ?? centers.get(components.get(id))), 0) / parents.length : centers.get(components.get(person.id)); const orbitRadius = Math.max(spacing, viewportWidth * 0.12 + (masses.get(parents[0]) || masses.get(person.id)) * 0.7); const childOffset = parents.length ? (siblings.length - 1) / 2 : 0; const orbitOffset = parents.length ? (siblingIndex - childOffset) * orbitRadius : 0; const spouseOffset = person.spouses.length ? (person.id < person.spouses[0] ? -spacing / 2 : spacing / 2) : 0; targets.set(person.id, parentCenter + orbitOffset + spouseOffset); });
  const x = new Map(targets);
  for (let iteration = 0; iteration < 30; iteration += 1) {
    groups.forEach(group => {
      group.forEach(person => {
        let force = (targets.get(person.id) - x.get(person.id)) * 0.12 - x.get(person.id) * 0.008;
        const linked = [person.father, person.mother, ...person.children, ...person.spouses].filter(id => id !== null);
        linked.forEach(id => {
          if (generations.get(id) === generations.get(person.id)) force += (x.get(id) - x.get(person.id)) * 0.025;
        });
        x.set(person.id, x.get(person.id) + force);
      });
      group.sort((a, b) => x.get(a.id) - x.get(b.id));
      for (let index = 1; index < group.length; index += 1) {
        x.set(group[index].id, Math.max(x.get(group[index].id), x.get(group[index - 1].id) + spacing));
      }
    });
  }
  let minimumX = 0; x.forEach(value => { minimumX = Math.min(minimumX, value); }); x.forEach((value, id) => x.set(id, value - minimumX + 24)); const y = new Map(); people.forEach(person => { const generation = generations.get(person.id) ?? 0; const parents = [person.father, person.mother].filter(id => id !== null); const siblings = parents.length ? people.filter(candidate => candidate.father === person.father && candidate.mother === person.mother) : []; const index = siblings.findIndex(sibling => sibling.id === person.id); const orbit = parents.length && siblings.length ? (index - (siblings.length - 1) / 2) * Math.min(34, viewportWidth * 0.035) : 0; y.set(person.id, 54 + generation * rowGap + orbit); }); return { x, y, masses, rowGap, width: Math.max(viewportWidth, Math.max(...x.values(), 0) + nodeWidth + 48) };
}
function relationLinks() { const links = []; people.forEach(person => { [person.father, person.mother].filter(id => id !== null).forEach(id => links.push([id, person.id, 'parent'])); person.spouses.forEach(id => { if (person.id < id) links.push([person.id, id, 'spouse']); }); }); return links; }
function startSimulation(generations, layout) {
  if (simulation?.frame) cancelAnimationFrame(simulation.frame);
  const width = Math.max(320, document.querySelector('.tree-scroll')?.clientWidth || 900); const height = Math.max(480, treeCanvas.clientHeight); const links = relationLinks(); const connected = new Set(links.flatMap(([first, second]) => [`${first}-${second}`, `${second}-${first}`]));
  const nodes = new Map(people.map(person => [person.id, { person, x: layout.x.get(person.id), y: layout.y.get(person.id), vx: 0, vy: 0, radius: Math.max(12, Math.min(38, 9 + layout.masses.get(person.id) / 2)) }]));
  simulation = { frame: 0, nodes };
  const tick = () => { if (!simulation || simulation.nodes !== nodes) return; const activeWidth = Math.max(width, people.length * 120); nodes.forEach(node => { node.vx *= .88; node.vy *= .88; node.vx += (width / 2 - node.x) * .0008; node.vy += (height / 2 - node.y) * .0005; });
    nodes.forEach(first => nodes.forEach(second => { if (first === second) return; const dx = second.x - first.x; const dy = second.y - first.y; const distance = Math.max(1, Math.hypot(dx, dy)); const sameComponent = connected.has(`${first.person.id}-${second.person.id}`); const minimum = first.radius + second.radius + 48; const repulsion = (sameComponent ? 0.7 : 1.8) * Math.max(0, minimum * 1.4 - distance) / distance; first.vx -= dx * repulsion; first.vy -= dy * repulsion; }));
    links.forEach(([firstId, secondId, kind]) => { const first = nodes.get(firstId); const second = nodes.get(secondId); if (!first || !second) return; const dx = second.x - first.x; const dy = second.y - first.y; const distance = Math.max(1, Math.hypot(dx, dy)); const desired = kind === 'spouse' ? 150 : Math.max(120, Math.min(260, width * .14 + first.radius + second.radius)); const spring = (distance - desired) * .004; first.vx += dx / distance * spring; first.vy += dy / distance * spring; second.vx -= dx / distance * spring; second.vy -= dy / distance * spring; });
    const byGeneration = new Map(); nodes.forEach(node => { const generation = generations.get(node.person.id) ?? 0; if (!byGeneration.has(generation)) byGeneration.set(generation, []); byGeneration.get(generation).push(node); }); byGeneration.forEach(group => { const targetY = 90 + [...byGeneration.keys()].sort((a, b) => a - b).indexOf([...byGeneration.keys()].find(key => byGeneration.get(key) === group)) * 190; group.forEach(node => { node.vy += (targetY - node.y) * .004; }); });
    nodes.forEach(node => { node.vx = Math.max(-12, Math.min(12, node.vx)); node.vy = Math.max(-12, Math.min(12, node.vy)); node.x += node.vx; node.y += node.vy; node.x = Math.max(24, Math.min(activeWidth - 24, node.x)); node.y = Math.max(24, Math.min(Math.max(height, 600) - 24, node.y)); const element = positions.get(node.person.id); if (element) { element.style.left = `${node.x}px`; element.style.top = `${node.y}px`; } });
    drawSolarConnections(nodes); simulation.frame = requestAnimationFrame(tick); }; tick();
}
function drawSolarConnections(nodes) { const bounds = treeCanvas.getBoundingClientRect(); connections.setAttribute('viewBox', `0 0 ${bounds.width} ${bounds.height}`); const center = id => { const node = nodes.get(id); const element = positions.get(id)?.querySelector('.node-dot'); if (!node || !element) return null; const box = element.getBoundingClientRect(); return { x: box.left + box.width / 2 - bounds.left, y: box.top + box.height / 2 - bounds.top, radius: box.width / 2 }; }; let markup = ''; relationLinks().forEach(([firstId, secondId, kind]) => { const first = center(firstId); const second = center(secondId); if (!first || !second) return; const dx = second.x - first.x; const dy = second.y - first.y; const distance = Math.max(1, Math.hypot(dx, dy)); const startX = first.x + dx / distance * first.radius; const startY = first.y + dy / distance * first.radius; const endX = second.x - dx / distance * second.radius; const endY = second.y - dy / distance * second.radius; markup += `<path class="edge-${kind}" d="M ${startX} ${startY} C ${(startX + endX) / 2} ${startY}, ${(startX + endX) / 2} ${endY}, ${endX} ${endY}"/>`; }); connections.innerHTML = markup; }
function render() {
  document.querySelector('#count').textContent = `${people.length} ${people.length === 1 ? 'person' : 'people'}`; document.querySelector('#statusText').textContent = people.length ? 'Map connected' : 'Empty map'; emptyAdd.hidden = people.length > 0; addDisconnected.hidden = people.length === 0;
  const generations = generationMap(); const viewportWidth = Math.max(320, document.querySelector('.tree-scroll')?.clientWidth || 900); const layout = layoutGraph(generations, viewportWidth); const maxGeneration = Math.max(0, ...generations.values()); positions = new Map(); peopleList.innerHTML = '';
  people.forEach(person => { const node = document.createElement('article'); node.className = `person gender-${person.gender} ${selectedId === person.id ? 'selected' : ''}`; node.dataset.id = person.id; node.style.left = `${layout.x.get(person.id)}px`; node.style.top = `${layout.y.get(person.id)}px`; node.style.setProperty('--mass', layout.masses.get(person.id)); node.style.setProperty('--mass-size', `${Math.max(12, Math.min(38, 9 + layout.masses.get(person.id) / 2))}px`); const birthday = yearOf(person); node.innerHTML = `<span class="node-dot"></span><h4>${escapeHtml(person.name)}</h4><div class="person-meta">${birthday || 'Unknown Birthday'}</div>`; peopleList.appendChild(node); positions.set(person.id, node); });
  peopleList.style.width = `${layout.width}px`; peopleList.style.height = `${Math.max(500, (maxGeneration + 2) * layout.rowGap)}px`; treeCanvas.style.minWidth = `${Math.max(980, layout.width)}px`; treeCanvas.style.minHeight = `${Math.max(580, (maxGeneration + 3) * layout.rowGap)}px`; yearBands.innerHTML = ''; startSimulation(generations, layout); if (selectedId !== null) placeBranchActions();
}
function drawConnections() { const bounds = treeCanvas.getBoundingClientRect(); connections.setAttribute('viewBox', `0 0 ${bounds.width} ${bounds.height}`); const box = id => positions.get(id)?.getBoundingClientRect(); const edge = (first, second, kind) => { const a = box(first); const b = box(second); if (!a || !b) return ''; const firstAbove = a.bottom <= b.top; const secondAbove = b.bottom <= a.top; let startX; let startY; let endX; let endY; if (firstAbove || secondAbove) { const source = firstAbove ? a : b; const target = firstAbove ? b : a; startX = source.left + source.width / 2 - bounds.left; startY = source.bottom - bounds.top; endX = target.left + target.width / 2 - bounds.left; endY = target.top - bounds.top; } else { const firstLeft = a.left < b.left; startX = (firstLeft ? a.right : a.left) - bounds.left; startY = a.top + a.height / 2 - bounds.top; endX = (firstLeft ? b.left : b.right) - bounds.left; endY = b.top + b.height / 2 - bounds.top; } const bend = firstAbove || secondAbove ? (startY + endY) / 2 : (startX + endX) / 2; const path = firstAbove || secondAbove ? `M ${startX} ${startY} C ${startX} ${bend}, ${endX} ${bend}, ${endX} ${endY}` : `M ${startX} ${startY} C ${bend} ${startY}, ${bend} ${endY}, ${endX} ${endY}`; return `<path class="edge-${kind}" d="${path}"/>`; }; const siblingGroups = new Map(); people.forEach(person => { if (person.father !== null && person.mother !== null) { const key = `${person.father}-${person.mother}`; if (!siblingGroups.has(key)) siblingGroups.set(key, []); siblingGroups.get(key).push(person); } }); const groupedChildren = new Set(); let markup = ''; siblingGroups.forEach(children => { if (children.length < 2) return; children.sort((a, b) => yearOf(a) - yearOf(b) || a.name.localeCompare(b.name)); const oldest = children[0]; if (!box(oldest.id) || !box(oldest.father) || !box(oldest.mother)) return; children.forEach(child => groupedChildren.add(child.id)); markup += edge(oldest.father, oldest.id, 'parent'); markup += edge(oldest.mother, oldest.id, 'parent'); children.slice(1).forEach(child => { markup += edge(oldest.id, child.id, 'parent'); }); }); people.forEach(person => { if (person.father !== null && !groupedChildren.has(person.id)) markup += edge(person.father, person.id, 'parent'); if (person.mother !== null && !groupedChildren.has(person.id)) markup += edge(person.mother, person.id, 'parent'); person.spouses.forEach(spouse => { if (person.id < spouse) markup += edge(person.id, spouse, 'spouse'); }); }); connections.innerHTML = markup; }
function selectPerson(id) { selectedId = id; document.body.classList.add('person-selected'); const person = people.find(entry => entry.id === id); if (!person) return; document.querySelector('#inspectorEmpty').hidden = true; editForm.hidden = false; document.querySelector('#avatar').textContent = person.name.slice(0, 1).toUpperCase(); document.querySelector('#personId').textContent = `PERSON ${person.id}`; document.querySelector('#editName').value = person.name; document.querySelector('#editBirthday').value = inputDate(person.birthday); populateRelationshipFields(person); branchActions.innerHTML = '<button title="Add father" aria-label="Add father" data-relation="parent" data-role="father">+<small>father</small></button><button title="Add mother" aria-label="Add mother" data-relation="parent" data-role="mother">+<small>mother</small></button><button title="Add sibling" aria-label="Add sibling" data-relation="sibling">+<small>sibling</small></button><button title="Add marriage" aria-label="Add marriage" data-relation="spouse">+<small>marriage</small></button><button title="Add child" aria-label="Add child" data-relation="child" data-role="father">+<small>child</small></button>'; branchActions.hidden = false; render(); }
function placeBranchActions() { const node = positions.get(selectedId); if (!node) return; const canvas = treeCanvas.getBoundingClientRect(); const box = node.getBoundingClientRect(); const width = branchActions.getBoundingClientRect().width; const center = box.left - canvas.left + box.width / 2; const clampedCenter = Math.max(width / 2 + 12, Math.min(canvas.width - width / 2 - 12, center)); branchActions.style.left = `${clampedCenter}px`; branchActions.style.top = `${box.bottom - canvas.top + 12}px`; }
function openCreate(relation = '', role = '') { createForm.reset(); createForm.elements.relation.value = relation; createForm.elements.relatedId.value = selectedId ?? ''; createForm.elements.role.value = role; document.querySelector('#createTitle').textContent = relation ? `Add ${relation}` : 'Add a person'; document.querySelector('#createKicker').textContent = relation ? `New ${relation} / connected to ${personName(selectedId)}` : 'New person'; dialog.showModal(); }
peopleList.addEventListener('click', event => { const node = event.target.closest('.person'); if (node) selectPerson(Number(node.dataset.id)); });
branchActions.addEventListener('click', event => { const button = event.target.closest('[data-relation]'); if (button) openCreate(button.dataset.relation, button.dataset.role || ''); });
document.querySelector('#addFirst').addEventListener('click', () => openCreate());
addDisconnected.addEventListener('click', () => openCreate());
document.querySelector('#closeInspector').addEventListener('click', () => { selectedId = null; document.body.classList.remove('person-selected'); editForm.hidden = true; document.querySelector('#inspectorEmpty').hidden = false; branchActions.hidden = true; render(); });
document.querySelector('#closeDialog').addEventListener('click', () => dialog.close());
async function updateRelationships(person) { const fatherId = editFather.value ? Number(editFather.value) : null; const motherId = editMother.value ? Number(editMother.value) : null; if (person.father !== fatherId) { if (person.father !== null) await request(`/api/relationships?childId=${person.id}&role=father`, { method: 'DELETE' }); if (fatherId !== null) await request('/api/relationships', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ childId: person.id, parentId: fatherId, role: 'father' }) }); } if (person.mother !== motherId) { if (person.mother !== null) await request(`/api/relationships?childId=${person.id}&role=mother`, { method: 'DELETE' }); if (motherId !== null) await request('/api/relationships', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ childId: person.id, parentId: motherId, role: 'mother' }) }); } const spouseId = editSpouse.value ? Number(editSpouse.value) : null; for (const existingId of person.spouses.filter(id => id !== spouseId)) await request(`/api/marriages?firstId=${person.id}&secondId=${existingId}`, { method: 'DELETE' }); if (spouseId !== null && !person.spouses.includes(spouseId)) await request('/api/marriages', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ firstId: person.id, secondId: spouseId }) }); }
editForm.addEventListener('submit', async event => { event.preventDefault(); try { const person = people.find(entry => entry.id === selectedId); await request('/api/people', { method: 'PATCH', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ id: selectedId, name: event.target.name.value, birthday: apiDate(event.target.birthday.value), gender: editGender.value }) }); await updateRelationships(person); await refresh(); selectPerson(selectedId); } catch (error) { document.querySelector('#statusText').textContent = error.message; } });
createForm.addEventListener('submit', async event => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(event.target)); data.birthday = apiDate(data.birthday); data.relatedId = data.relatedId ? Number(data.relatedId) : null; await request('/api/people', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(data) }); dialog.close(); await refresh(); } catch (error) { document.querySelector('#statusText').textContent = error.message; } });
window.addEventListener('resize', render);
async function refresh() { people = (await request('/api/people')).map(normalizePerson); render(); }
async function loadSavedTree() { const files = await request('/api/savefiles'); if (!files.length) return; savedTree.innerHTML = files.map(file => `<option value="${escapeHtml(file)}">${escapeHtml(file)}</option>`).join(''); loadDialog.showModal(); }
loadForm.addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/load', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ treename: savedTree.value }) }); loadDialog.close(); await refresh(); } catch (error) { document.querySelector('#statusText').textContent = error.message; } });
document.querySelector('#skipLoad').addEventListener('click', () => loadDialog.close());
loadSavedTree().then(refresh).catch(error => { document.querySelector('#statusText').textContent = error.message; });
document.querySelector('#savePeople').addEventListener('click', () => { saveName.value = ''; saveDialog.showModal(); });
document.querySelector('#closeSaveDialog').addEventListener('click', () => saveDialog.close());
saveForm.addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/save', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ treename: saveName.value.trim() }) }); saveDialog.close(); document.querySelector('#statusText').textContent = `Saved ${saveName.value.trim()}.save`; } catch (error) { document.querySelector('#statusText').textContent = error.message; } });
document.querySelector('#clearPeople').addEventListener('click', async () => { if (!people.length || !confirm('Clear every person from the family map?')) return; try { await request('/api/people', { method: 'DELETE' }); selectedId = null; document.querySelector('#inspectorEmpty').hidden = false; editForm.hidden = true; branchActions.hidden = true; await refresh(); } catch (error) { document.querySelector('#statusText').textContent = error.message; } });
